project:
  type: book
  output-dir: docs
book:
  title: An Introduction to Python for Healthcare Services
  author: Sammi Rosser
  chapters:
  - index.qmd
  - that's_very_variable.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js