project:
  type: book

book:
  title: "An Introduction to Python for Health"
  author: "Sammi Rosser"
  date: "22/02/2024"
  chapters:
    - index.qmd
    - hello_world.qmd
    - that's_very_variable.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

